# Generated by Django 2.2.13 on 2021-03-09 13:35

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_auto_20210309_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_height', null=True, upload_to='presenters/', verbose_name='Image 1n', width_field='image_width'),
        ),
    ]
