# Generated by Django 2.2.13 on 2021-03-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_auto_20210309_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presenter',
            old_name='image_alt',
            new_name='image_alt_1',
        ),
    ]
